




















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `default`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `server=52.233.153.36;user=caasdbadmin;database=caasdb;port=3306;password=**zapped**;`
//     Schema:                 `CaaSdb`
//     Include Views:          `False`


// -----------------------------------------------------------------------------------------
// Failed to load provider `MySql.Data.MySqlClient` - Unable to find the requested .Net Framework Data Provider.  It may not be installed.
// -----------------------------------------------------------------------------------------




